// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmN5NUOBrSPc_o2sCouQPoS416RUMc62U',
    appId: '1:24269320454:ios:84a133f40821942a422e87',
    messagingSenderId: '24269320454',
    projectId: 'nabizolcer-2ff75',
    databaseURL: 'https://nabizolcer-2ff75-default-rtdb.firebaseio.com',
    storageBucket: 'nabizolcer-2ff75.firebasestorage.app',
    iosBundleId: 'com.example.nabiz',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuvRN1SL7dmAGqZopxsMEEuSAcqU4byVo',
    appId: '1:24269320454:android:b5ec848b7c2cbc94422e87',
    messagingSenderId: '24269320454',
    projectId: 'nabizolcer-2ff75',
    databaseURL: 'https://nabizolcer-2ff75-default-rtdb.firebaseio.com',
    storageBucket: 'nabizolcer-2ff75.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA5HRw5Vw2hBQ3HFcIxpB7AxbjIDAmoGs',
    appId: '1:24269320454:web:0cb4727b3bda0da0422e87',
    messagingSenderId: '24269320454',
    projectId: 'nabizolcer-2ff75',
    authDomain: 'nabizolcer-2ff75.firebaseapp.com',
    databaseURL: 'https://nabizolcer-2ff75-default-rtdb.firebaseio.com',
    storageBucket: 'nabizolcer-2ff75.firebasestorage.app',
    measurementId: 'G-1S2R6PYJTS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmN5NUOBrSPc_o2sCouQPoS416RUMc62U',
    appId: '1:24269320454:ios:84a133f40821942a422e87',
    messagingSenderId: '24269320454',
    projectId: 'nabizolcer-2ff75',
    databaseURL: 'https://nabizolcer-2ff75-default-rtdb.firebaseio.com',
    storageBucket: 'nabizolcer-2ff75.firebasestorage.app',
    iosBundleId: 'com.example.nabiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA5HRw5Vw2hBQ3HFcIxpB7AxbjIDAmoGs',
    appId: '1:24269320454:web:7c147beed8e0082e422e87',
    messagingSenderId: '24269320454',
    projectId: 'nabizolcer-2ff75',
    authDomain: 'nabizolcer-2ff75.firebaseapp.com',
    databaseURL: 'https://nabizolcer-2ff75-default-rtdb.firebaseio.com',
    storageBucket: 'nabizolcer-2ff75.firebasestorage.app',
    measurementId: 'G-T0D9039F78',
  );

}